---
- name: "Set git_repo_url based on env_type"
  set_fact:
    git_repo_url: "{{ env_repos[env_type] }}"
    git_branch: "{{ env_branch[env_type] }}"

- name: Extract repo_basename from repo_url using regex
  set_fact:
    repo_basename: "{{ git_repo_url | regex_replace('^.*/', '') | regex_replace('\\.git$', '') }}"

- name: Debug repo_basename
  debug:
    var: repo_basename

- name: Ensure .netrc for GitHub authentication
  copy:
    dest: "{{ ngsraw_home }}/.netrc"
    mode: '0600'
    owner: "{{ ngsraw_username }}"
    group: "{{ discovered_gid }}"
    content: |
      machine github.com
      login {{ github_username }}
      password {{ github_pat }}
  no_log: true
  
- name: "Clone scripts from {{ git_repo_url }} as {{ ngsraw_username }}"
  become: true
  become_user: "{{ ngsraw_username }}"
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_branch}}"
    dest: "{{ ngsraw_home }}/{{ repo_basename }}"
    update: yes
    force: yes #  fresh clone