---
- name: "Set git_repo_url based on env_type"
  set_fact:
    git_repo_url: "{{ env_repos[env_type] }}"
    git_branch: "{{ env_branch[env_type] }}"

- name: Extract repo_basename from repo_url using regex
  set_fact:
    repo_basename: "{{ git_repo_url | regex_replace('^.*/', '') | regex_replace('\\.git$', '') }}"

- name: Debug repo_basename
  debug:
    var: repo_basename

- name: Ensure destination directory exists with correct permissions and sticky bit
  file:
    path: "{{ ngsraw_home }}/{{ repo_basename }}"
    state: directory
    owner: "{{ ngsraw_username }}"
    group: "{{ discovered_gid }}"
    mode: '2775'  # rwxrwsr-x with setgid bit set

- name: "Clone scripts from {{ git_repo_url }}"
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_branch}}"
    dest: "{{ ngsraw_home }}/{{ repo_basename }}"
    update: yes
    force: yes #  fresh clone