# 1) Check if user 'ngsraw' is known to the system (e.g., via IdM, LDAP, or SSSD)
- name: Check if ngsraw user exists in IdM
  getent:
    database: passwd
    key: "{{ ngsraw_username }}"
  register: user_info

# Fail if user does not exist in IdM
- name: Fail if user is absent in IdM
  fail:
    msg: "User '{{ ngsraw_username }}' not found in IdM. Please create it centrally first!"
  when:
    - user_info.ansible_facts.getent_passwd is not defined
      or user_info.ansible_facts.getent_passwd[ngsraw_username] is not defined
      or user_info.ansible_facts.getent_passwd[ngsraw_username] | length == 0

# Parse out the home directory and numeric UID/GID
- name: Extract ID and home info
  set_fact:
    discovered_uid: "{{ user_info.ansible_facts.getent_passwd[ngsraw_username][1] | int }}"
    discovered_gid: "{{ user_info.ansible_facts.getent_passwd[ngsraw_username][2] | int }}"
    discovered_home: "{{ user_info.ansible_facts.getent_passwd[ngsraw_username][4] }}"

- name: Debug all discovered user info
  debug:
    msg:
      discovered_uid: "{{ discovered_uid }}"
      discovered_gid: "{{ discovered_gid }}"
      discovered_home: "{{ discovered_home }}"

# Overwrite ngsraw_home with the discovered directory, if available
- name: Set ngsraw_home to system home if discovered from IdM
  set_fact:
    ngsraw_home: "{{ discovered_home }}"
  when:
    - discovered_home is defined
    - discovered_home | length > 0

# Ensure user’s home directory is present
- name: Create home directory if missing
  file:
    path: "{{ ngsraw_home }}"
    state: directory
    owner: "{{ ngsraw_username }}"
    group: "{{ discovered_gid }}"
    mode: '0700'
  # If the system-provided home dir is blank or undefined,
  # fallback to {{ ngsraw_home }} from your defaults.

# Ensure .ssh directory is present
- name: Create .ssh directory
  file:
    path: "{{ ngsraw_home }}/.ssh"
    state: directory
    owner: "{{ ngsraw_username }}"
    group: "{{ discovered_gid }}"
    mode: '0700'

# Check if user already has an SSH key
- name: Check if SSH key exists
  stat:
    path: "{{ ngsraw_home }}/.ssh/id_{{ ssh_key_type }}"
  register: ssh_key

# Generate SSH key if missing
- name: Generate SSH key for ngsraw if none exists
  become_user: "{{ ngsraw_username }}"
  command: ssh-keygen -t {{ ssh_key_type }} \
           -f {{ ngsraw_home }}/.ssh/id_{{ ssh_key_type }} \
           -N ''
  args:
    creates: "{{ ngsraw_home }}/.ssh/id_{{ ssh_key_type }}"
  when: not ssh_key.stat.exists
